# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cbb431a86a25bed3430e45f2c7f3e5476fce17b220b04805a7123892d6fb50720d7b1e04eab8f56bf486cd9035dc775d5ec655253ac5c6268e5975fc7151cec

test:
  secret_key_base: 5530b9a097aea30ce1044a897bdaa05298363583574964de560c2d616822a75758adb4fa4a115be7feb7920f7faa1c99a80850751d344b1761b083b14bf84aab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
